### ISSUE TITLE
Crop interface

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#13]

**Comment by susannaanas** [comment]
There are drafts for an enhanced crop interface. There are some enhancements needed with the functionality of the current interface, but they could also be handled as tweaks of the current environment.

**Comment by susannaanas** [comment]
# Place first point

Hover
![crop - seek first point-02](https://cloud.githubusercontent.com/assets/4725416/5450484/067cae54-850f-11e4-9f49-24d8832b81e5.png)
On click (image needed)

# Place second point

Hover
![crop - seek second point - line-03](https://cloud.githubusercontent.com/assets/4725416/5450485/068a5176-850f-11e4-951e-811764a0b385.png)
Alternative design
![crop - seel second point-03](https://cloud.githubusercontent.com/assets/4725416/5450486/068a5338-850f-11e4-9188-731aa469d85f.png)

# Add point

![crop - add point-04](https://cloud.githubusercontent.com/assets/4725416/5450479/06633aa0-850f-11e4-9f2e-c5168f5be117.png)
Needs more visible cursor, and more defined cursor state when adding a point

# Select point

![crop - select point-04](https://cloud.githubusercontent.com/assets/4725416/5450488/0690a7ec-850f-11e4-8905-1a8e5cb6cf8b.png)
Same as previous: Needs more defined cursor states

# Edit point

![crop - edit point-04](https://cloud.githubusercontent.com/assets/4725416/5450483/067a7454-850f-11e4-9000-177b83d9061d.png)
Point selected shows a ring around the point and the action menu. Radial menu might be abandoned.

# Drag point

![crop - drag point-04](https://cloud.githubusercontent.com/assets/4725416/5450482/0674cbee-850f-11e4-9b5f-ffa823cb2602.png)
Shows lens when point is dragged. On release returns to edit state.

# Close path

![crop - close path-02](https://cloud.githubusercontent.com/assets/4725416/5450480/06684158-850f-11e4-969a-0f9655ef4f60.png)
Mask should be changed to inverse, showing masked areas rather than covering the map

# Further design

An alternative (better) masking starting point could be a masked rectangle that can be modified.

**Comment by timwaters** [comment]
Closing this as the plan now is for mapwarper to just act as an API. 
The front end would be in another project
