### ISSUE TITLE
new?pageid=... sometimes fails to identify existing maps

### ISSUE THREAD

**Issue by lokal-profil** [wikimaps-dev/mapwarper#41]
Visiting https://warper.wmflabs.org/wikimaps/new?pageid=... should trigger a new upload or redirect to an existing file as appropriate. Sometimes however this seems not to work.

Example:
- `https://warper.wmflabs.org/wikimaps/new?pageid=32759093` should identify that this is the same as `https://warper.wmflabs.org/maps/68` but doesn't.
- `https://warper.wmflabs.org/wikimaps/new?pageid=38199022` on the other hand works fine.

**Comment by timwaters** [comment]
This is due to the file being a tiff file.

https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Ekonomiska_kartan_20K7D_%28Ume%C3%A5_v%C3%A4stra_J133-20K7d61%29.tiff/lossy-page1-614px-Ekonomiska_kartan_20K7D_%28Ume%C3%A5_v%C3%A4stra_J133-20K7d61%29.tiff.jpg

https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Ekonomiska_kartan_20K7D_%28Ume%C3%A5_v%C3%A4stra_J133-20K7d61%29.tiff/300px-Ekonomiska_kartan_20K7D_%28Ume%C3%A5_v%C3%A4stra_J133-20K7d61%29.tiff.png

this is handled by the pagedtiff extension in mediawiki

the special things are instead of 300px we have to put lossy-page1-614px  (assuming page1 is what we need) 

and instead of png, we have to use jpg

**Comment by timwaters** [comment]
for png - specify lossless

https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Ekonomiska_kartan_20K7D_%28Ume%C3%A5_v%C3%A4stra_J133-20K7d61%29.tiff/lossless-page1-120px-Ekonomiska_kartan_20K7D_%28Ume%C3%A5_v%C3%A4stra_J133-20K7d61%29.tiff.png

**Comment by timwaters** [comment]
The actual bug where it is not detecting if it's a duplicate or not has already been fixed, as we now check using the pageid itself. 

Closing. also adding in fix for the tiff files and thumbs
