### ISSUE TITLE
Getting error often while warping

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#55]
Sorry, there appears to be an error sending the request to the server, try again?...

Map http://warper.wmflabs.org/maps/281#Rectify_tab logged in as susannaanas

**Comment by timwaters** [comment]
Was this seen on every map?

This is due to the updating of the commons file page.

**Comment by susannaanas** [comment]
I keep leaving the process when it happens and I am not sure how it goes. I
will try to observe more systematically. Still I would say most of the
times.

2015-12-05 17:52 GMT+02:00 Tim Waters notifications@github.com:

**Comment by timwaters** [comment]
I mean, does this happen on just map 281 or does it happen on other maps, or every map?

**Comment by timwaters** [comment]
I believe I have identified the bug. It's due to html comments in the wiki page
https://commons.wikimedia.org/w/index.php?title=File:Senate_Atlas,_1870%E2%80%931907._Sheet_IV_22_Tammisaari.jpg&action=edit  containing warped and latitude parameters etc

This data in the comment is sent via the api to the warper and the warper treats it as normal

**Comment by susannaanas** [comment]
This kind of data exists in all the maps uploaded by the GWToolset.

I am doing another test and it does seem that the warping never ends. When I return to the page after reloading something is done, however. Adding control points is not problematic.

**Comment by timwaters** [comment]
Yes, the error is due to reading and changing the wiki page, not in the actual warping. a fix is coming

**Comment by susannaanas** [comment]
Yes, rectifying never stopped but the image was however warped.

**Comment by timwaters** [comment]
Okay I have committed and deployed the fix for this.

We may have to revisit the code that parses the wiki page if there are pages with complex layouts and templates... But will have to see how this goes.

The code will also fail silently to the user if there are similar errors now - but it will at least show the warped map. Any errors will be logged however.

**Comment by susannaanas** [comment]
Great!!
