### ISSUE TITLE
Warper down

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#67]
An error occurred while starting up the preloader: it did not write a startup response in time.
Application root
/var/www/apps/wikimapswarper/mapwarper
Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV and PASSENGER_ENV)
production
Ruby interpreter command
/home/chippy/.rvm/wrappers/ruby-1.9.3-p551@rails4/ruby
User and groups
Unknown
Environment variables
Unknown
Ulimits
Unknown

**Comment by timwaters** [comment]
We should not use github for these types of issues. Issues are for bugs, improvements etc. 
Please email, or use phabricator for infrastructure things. Github is for the application, rather than the server, the warper not the machine it runs on :-)

However in this case, this is because of a recent labs wide work and reboot. 

I'll close this in the meantime, and will communicate off github

**Comment by timwaters** [comment]
Tracking this here: https://phabricator.wikimedia.org/T124538
